# Generated by Django 4.0.6 on 2022-09-01 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('fathername', models.CharField(max_length=245)),
                ('starts_on', models.CharField(max_length=100)),
                ('ends_on', models.CharField(max_length=100)),
            ],
        ),
    ]
