# Generated by Django 4.0.6 on 2022-09-06 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extechapp', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
